version: '3'
services:
  database:
    container_name: database
    build: .
    image: database
    environment: 
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: kamin124712
      MYSQL_DATABASE: cfandb
    volumes:
      - "./scripts/cfan.sql:/docker-entrypoint-initdb.d/cfan.sql"
    ports:
      - "3306:3306"
    networks:
      allnetwork:
        ipv4_address: 172.20.0.4

networks:
    default:
      external:
        name: allnetwork
    allnetwork:
      external: true
